---
all:
  children:
    gb10:
      children:
        gb10_head:
          hosts:
            gothi.local:
              ansible_host: 10.255.0.50
              vllm_role: head
              cx7_node_ip: 10.10.0.1
        gb10_worker:
          hosts:
            gethli.local:
              ansible_host: 10.255.0.51
              vllm_role: worker
              cx7_node_ip: 10.10.0.2
